export const USER_REGISTER = "USER_REGISTER";
export const USER_LOGIN = "USER_LOGIN";
export const USER_GET_ME = "USER_GET_ME";
export const USER_LOG_OUT = "USER_LOG_OUT";
export const USER_ERROR = "USER_ERROR";

export const POST_GET_POSTS = "POST_GET_POSTS";
export const POST_GET_POST = "POST_GET_POST";
export const POST_MORE_POSTS = "POST_MORE_POSTS";
export const POST_ERROR = "POST_ERROR";

export const REGISTER_PENDING = "REGISTER_PENDING";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";
export const LOG_IN_PENDING = "LOG_IN_PENDING";
export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS";
export const LOG_IN_ERROR = "LOG_IN_ERROR";
export const GET_CURRENT_USER_PENDING = "GET_CURRENT_USER_PENDING";
export const GET_CURRENT_USER_SUCCESS = "GET_CURRENT_USER_SUCCESS";
export const GET_CURRENT_USER_ERROR = "GET_CURRENT_USER_ERROR";
export const LOG_OUT_PENDING = "LOG_OUT_PENDING";
export const LOG_OUT_SUCCESS = "LOG_OUT_SUCCESS";
export const LOG_OUT_ERROR = "LOG_OUT_ERROR";

export const FIREBASE_GET_POSTS = "FIREBASE_GET_POSTS";
export const FIREBASE_GET_POST = "FIREBASE_GET_POST";
export const FIREBASE_CREATE_POST = "FIREBASE_CREATE_POST";
export const FIREBASE_DELETE_POST = "FIREBASE_DELETE_POST";
export const FIREBASE_UPDATE_POST = "FIREBASE_UPDATE_POST";
export const FIREBASE_POST_ERROR = "FIREBASE_POST_ERROR";
